name: Checks

on:
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    container: cypress/included:5.1.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Report
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run test:coverage"
          changes-only: true
